name: 'oncovault'
version: '1.0.0'

profile: 'oncovault'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  initial_batch_date: "2026-01-01"

models:
  oncovault:
    +materialized: view
    dcl:
      +schema: dcl
      +materialized: table
