version: 2

sources:
  - name: tidywigits
    schema: tidywigits
    tables:
      - name: alignments_dupfreq
      - name: amber_bafpcf
      - name: amber_contaminationtsv
      - name: amber_homozygousregion
      - name: amber_qc
      - name: amber_version
      - name: bamtools_coverage
      - name: bamtools_exoncvg
      - name: bamtools_flagstats
      - name: bamtools_fraglength
      - name: bamtools_genecvg_cvg
      - name: bamtools_genecvg_genes
      - name: bamtools_partitionstats
      - name: bamtools_summary_dp
      - name: bamtools_summary_stats
      - name: chord_prediction
      - name: chord_signatures
      - name: cider_blastn
      - name: cider_locusstats
      - name: cider_vdj
      - name: cobalt_gcmed_buckets
      - name: cobalt_gcmed_sample
      - name: cobalt_ratiomed
      - name: cobalt_ratiopcf
      - name: cobalt_version
      - name: cuppa_predsum
      - name: cuppa_visdata
      - name: esvee_assemblealignment
      - name: esvee_assembleassembly
      - name: esvee_assemblebreakend
      - name: esvee_assemblephased
      - name: esvee_prepdiscstats
      - name: esvee_prepfraglen
      - name: esvee_prepjunction
      - name: lilac_qc
      - name: lilac_summary
      - name: linx_breakends
      - name: linx_clusters
      - name: linx_drivercatalog
      - name: linx_drivers
      - name: linx_fusions
      - name: linx_links
      - name: linx_neoepitope
      - name: linx_svs
      - name: linx_version
      - name: linx_viscn
      - name: linx_visfusion
      - name: linx_visgeneexon
      - name: linx_visproteindomain
      - name: linx_vissegments
      - name: linx_vissvdata
      - name: metadata
      - name: neo_candidates
      - name: neo_predictions
      - name: peach_events
      - name: peach_geneevents
      - name: peach_haplotypesall
      - name: peach_haplotypesbest
      - name: peach_qc
      - name: purple_cnvgenetsv
      - name: purple_cnvsomtsv
      - name: purple_drivercatalog
      - name: purple_germdeltsv
      - name: purple_purityrange
      - name: purple_puritytsv
      - name: purple_qc
      - name: purple_somclonality
      - name: purple_somhist
      - name: purple_version
      - name: sage_bqrtsv
      - name: sigs_allocation
      - name: sigs_snvcounts
      - name: teal_breakend
      - name: teal_tellength
      - name: virusbreakend_vcfsummary
      - name: virusinterpreter_annotated
